/**
 * Pre-generated immersive moments for demo paragraphs.
 * Generated by scripts/generateMomentCache.mjs -- do not edit manually.
 *
 * Data is lazy-loaded from /momentCache.json at runtime to reduce bundle size.
 */

import type { KeyMoment } from '../services/momentsService';

/** Key format: "{grade}-{paragraphIndex}" e.g. "K-0", "3-2", "6-1" */
let cache: Record<string, KeyMoment[]> | null = null;
let loadPromise: Promise<Record<string, KeyMoment[]>> | null = null;

async function loadCache(): Promise<Record<string, KeyMoment[]>> {
  if (cache) return cache;
  if (loadPromise) return loadPromise;

  loadPromise = fetch('/momentCache.json')
    .then((res) => res.json())
    .then((data: Record<string, KeyMoment[]>) => {
      cache = data;
      return data;
    })
    .catch(() => {
      cache = {};
      return {};
    });

  return loadPromise;
}

/**
 * Synchronous access to the cached data.
 * Returns the cache if already loaded, or an empty object.
 * Call `ensureMomentCacheLoaded()` first for guaranteed availability.
 */
export const momentCache: Record<string, KeyMoment[]> = new Proxy({} as Record<string, KeyMoment[]>, {
  get(_target, prop: string) {
    return cache?.[prop];
  },
  has(_target, prop: string) {
    return cache ? prop in cache : false;
  },
});

/** Pre-load the moment cache. Call early in the app lifecycle. */
export async function ensureMomentCacheLoaded(): Promise<void> {
  await loadCache();
}
